services:

  # Reverse proxy - reçoit le trafic HTTP
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    depends_on:
      - app

  # WordPress - le site web
  app:
    image: wordpress:latest
    env_file:
      - .env
    ports:
      - "8081:80" 
    volumes:
      - wp_data:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - db

  # MySQL - la base de données
  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

#Les variables de nos volumes
volumes:
  wp_data:
  db_data:

#Les variables de notre Network
networks:
  frontend:
  backend: